name: WhatsApp/Telegram Bot Scheduler

on:
  schedule:
    # Define o horário que você quer que o bot execute. (Esse exemplo roda todo dia às 14:00 UTC)
    - cron: '0 14 * * *'
  workflow_dispatch: # Para rodar manualmente

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twilio schedule python-telegram-bot

      - name: Run the bot
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python bot.py  # Supondo que seu código esteja em bot.py
